# Generated by Django 5.2.9 on 2026-02-06 17:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('source', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('olx', 'OLX'), ('rozetka', 'Rozetka'), ('website', 'Сайт'), ('referral', 'Рекомендація'), ('other', 'Інше')], default='other', max_length=20, verbose_name='Джерело')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ціна закупівлі')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ціна продажу')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Залишок на складі')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новий'), ('confirmed', 'Підтверджено'), ('shipped', 'Відправлено'), ('completed', 'Виконано'), ('canceled', 'Скасовано'), ('returned', 'Повернення')], default='new', max_length=20, verbose_name='Статус')),
                ('delivery_service', models.CharField(choices=[('nova_poshta', 'Нова Пошта'), ('ukrposhta', 'Укрпошта'), ('meest', 'Meest'), ('pickup', 'Самовивіз')], default='nova_poshta', max_length=20, verbose_name='Служба доставки')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('warehouse', models.CharField(blank=True, max_length=255, verbose_name='Відділення')),
                ('ttn', models.CharField(blank=True, max_length=50, verbose_name='ТТН')),
                ('payment_type', models.CharField(choices=[('cod', 'Накладений платіж'), ('prepaid', 'Передплата'), ('partial', 'Часткова передплата')], default='cod', max_length=20, verbose_name='Тип оплати')),
                ('prepayment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Передплата')),
                ('seller_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Додаткові витрати (пакування, доставка тощо)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Витрати продавця')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.customer', verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кількість')),
                ('price', models.DecimalField(decimal_places=2, help_text='Фіксована ціна на момент замовлення', max_digits=10, verbose_name='Ціна за одиницю')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Замовлення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='orders.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар замовлення',
                'verbose_name_plural': 'Товари замовлення',
            },
        ),
    ]
